version: '3'

services: 
  front:
    # build: ./front_react
    image: nginx:latest
    restart: always
    ports: 
      - "80:80"
    container_name: nginx-front
    volumes:
      - ./build-react:/usr/share/nginx/html 



  back:
    build: ./api
    container_name: back-end
    restart: always
    ports: 
      - "5000:5000"
    depends_on:
      - mongo




  mongo:
    image: mongo
    restart: always
    container_name: localhost
    ports:
      - 27017:27017



